//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camiones
    {
        public int ID_Camion { get; set; }
        public string Matricula { get; set; }
        public string Tipo_Camion { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Capacidad { get; set; }
        public double Kilometraje { get; set; }
        public string UrlFoto { get; set; }
        public bool Disponibilidad { get; set; }
    }
}
