//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rutas()
        {
            this.Cargamentos = new HashSet<Cargamentos>();
        }
    
        public int ID_Ruta { get; set; }
        public int Camion_ID { get; set; }
        public Nullable<double> Distancia { get; set; }
        public Nullable<System.DateTime> Fecha_salida { get; set; }
        public Nullable<System.DateTime> Fecha_llegadaestimada { get; set; }
        public Nullable<System.DateTime> Fecha_llegadareal { get; set; }
        public Nullable<int> Chofer_ID { get; set; }
        public Nullable<int> Direccionorigen_ID { get; set; }
        public Nullable<int> Direcciondestino_ID { get; set; }
    
        public virtual Camiones Camiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargamentos> Cargamentos { get; set; }
        public virtual Choferes Choferes { get; set; }
        public virtual Direcciones Direcciones { get; set; }
        public virtual Direcciones Direcciones1 { get; set; }
    }
}
