//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Rutas
    {
        public int C_ { get; set; }
        public int ID_Cargamento { get; set; }
        public string cargamento { get; set; }
        public int ID_Direccion_Origen { get; set; }
        public string Origen { get; set; }
        public string Estado_Origen { get; set; }
        public int ID_Direccion_Destino { get; set; }
        public string Destino { get; set; }
        public string Estado_Destino { get; set; }
        public int ID_Chofer { get; set; }
        public string Chofer { get; set; }
        public int ID_Camion { get; set; }
        public string Camión { get; set; }
        public Nullable<System.DateTime> Salida { get; set; }
        public Nullable<System.DateTime> LLegada_Estimada { get; set; }
    }
}
